[project]
name = "clicue"
version = "0.1.32"

description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["rapidfuzz", "vosk", "sounddevice", "rich", "faster-whisper"]

[project.scripts]
clicue = "clicue.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
only-include = ["src/clicue", "README.md", "pyproject.toml"]

[tool.hatch.build.targets.wheel]
packages = ["src/clicue"]

[dependency-groups]
dev = [
    "verkit",
]


